[package]
name = "FOMOSv2_CL"
version = "2.3.5"
edition = "2018"


[lib]
name = "FOMOSv2_CL"
crate-type = ["staticlib"]
path = "src/lib.rs"


[workspace]
members = [
    "kernel/",
    "arch/",
]


[dependencies]
bootloader = "0.9.11"
arch = { path = "arch/" }
kernel = { path = "kernel/" }
