[package]
name = "FOMOSv2"
version = "2.3.5"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.11"

[build-dependencies]
cc = "1.0.62"
