[package]
name = "FOMOS"
version = "2.3.5"
edition = "2018"

[lib]
name = "FOMOS"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.80"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"

[build-dependencies]
cc = "1.0.61"
pkg-config = "0.3.19"
