[package]
name = "FOMOS"
version = "2.3.5"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2.80"
serde_json = "1.0.59"

[build-dependencies]
cc = "1.0.61"
pkg-config = "0.3.19"
