[package]
name = "FOMOSv2CL"
version = "2.3.5"
edition = "2018"


[[bin]]
name = "FOMOSv2CL"
path = "FOMOSv2/src/main.rs"


[dependencies]
bootloader = "0.9.11"
arch = { path = "arch/" }


[workspace]
members = [
    "FOMOSv2",
    "arch",
]

