[package]
name = "FOMOSv2_CL"
version = "2.3.5"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.18"

[dependencies.novusk]
git = "https://github.com/NathanMcMillan54/novusk"
tag = "v3-beta-k2"
features = ["bios_boot"]
