[package]
name = "kernel"
version = "2.0.0"
authors = ["Nathan McMillan"]
edition = "2018"

# The features section is used to select the target board.
[features]
default = []
bsp_rpi3 = []
bsp_rpi4 = []

[dependencies]