[package]
name = "FOMOS"
version = "2.3.5"
edition = "2018"

[lib]
name = "FOMOS"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
libc = "0.2.80"

[build-dependencies]
cc = "1.0.61"
