[package]
name = "qmk-keymap"
version = "0.1.0"
edition = "2018"

[lib]
name = "keymap"
crate-type = ["staticlib"]
path = "rust/lib.rs"

[dependencies]
paste = "0.1"

[build-dependencies]
bindgen = "0.*"