# [build]
# target = "x86_64-unknown-linux-gnu"
# target = "armv7-unknown-linux-gnueabihf"
# target = "armv6-unknown-linux-gnueabihf"

# [unstable]
# build-std = ["core", "compiler_builtins"]
# build-std-features = ["compiler-builtins-mem"]