[package]
name = "fomos"
version = "0.1.0"
edition = "2018"

[dependencies]
fk_std = "0.2.3"
builtin_commands = { git = "https://github.com/sbFomos/builtin_commands", branch = "testing" }

[build-dependencies]
cc = "1.0.66"
