[package]
name = "fomos"
version = "0.1.0"
edition = "2018"

[dependencies]
fk_std = "0.3.3"
builtin_commands = { git = "https://github.com/NathanMcMillan54/builtin_commands" }

[build-dependencies]
cc = "1.0.66"
